### ISSUE TITLE
 unexpected keyword argument 'tweets'

### ISSUE THREAD

**Issue by cifinn** [neo4j-examples/twitter-graph-viz#5]
oscon+OR+neo4j+OR+%23oscon+OR+%40neo4j
Found 100 tweets.
execute() got an unexpected keyword argument 'tweets'

**Comment by jexp** [comment]
Are you using py2neo 2 or 3 ?

**Comment by cifinn** [comment]
I initially started using the latest verison but then downgraded to 2.1.5 and saw no change.

**Comment by karlfloersch** [comment]
@cifinn did you find a solution?

**Comment by cifinn** [comment]
@karlfloersch If I remember correctly, I'm pretty sure the problem arises when the code tries to parse non-existent attributes from the Twitter search response. If you read https://dev.twitter.com/rest/reference/get/search/tweets you will get an idea as to what expected from the API. For example, checkout https://github.com/neo4j-examples/twitter-graph-viz/blob/master/import.py#L73. The code is attempting to parse `u.statusus_count` . My guess is that this should be corrected to be `u.statuses_count`. Otherwise, I'd recommend the implementation of better error handling for the cases where JSON attributes don't exist. Hope this helps.

**Comment by jexp** [comment]
@karlfloersch @cifinn 

I updated it to the neo4j-python-driver for bolt and also fixed the twitter search API changes. Have fun.
